// This placeholder type will be regenerated by Supabase CLI in Phase 2 after the DB schema is created.
export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
